import { useEffect, useMemo, useState } from 'react'

const API = '/api'
const auth = () => ({ Authorization: `Bearer ${localStorage.getItem('token') || ''}` })
const jsonHeaders = () => ({ ...auth(), 'Content-Type': 'application/json' })
const money = (value) => `$${Number(value || 0).toLocaleString('es-CO')}`
const routes = [['Dashboard', '/dashboard', '⌂'], ['Finanzas', '/finanzas', '◈'], ['Chat IA', '/chat', '✦'], ['Calendario', '/calendario', '▣'], ['Recomendaciones', '/recomendaciones', '✧'], ['Simulador', '/simulador', '↗'], ['Aprende', '/aprende', '▤'], ['Perfil', '/perfil', '◉'], ['Exportar', '/exportar', '⇩']]

async function request(path, options = {}) {
  const response = await fetch(`${API}${path}`, options)
  const data = await response.json().catch(() => ({}))
  if (!response.ok) throw new Error(data.detail || data.mensaje || 'No se pudo completar la solicitud')
  return data
}

export function Shell({ title, subtitle, active, children }) {
  const user = JSON.parse(localStorage.getItem('usuario') || 'null')
  return <div className="react-shell"><aside className="app-sidebar"><div className="app-brand"><span><img src="/images/logo.png" alt="FinanBot" /></span><strong>FinanBot</strong></div><nav>{routes.map(([label, href, icon]) => <a className={active === href ? 'active' : ''} href={href} key={href}><i>{icon}</i>{label}</a>)}</nav><div className="app-sidebar-bottom"><button onClick={() => { localStorage.clear(); location.href = '/login' }}>⇥ Cerrar sesión</button><span><i /> API conectada</span></div></aside><main className="app-content"><header className="app-topbar"><div><p className="eyebrow">FinanBot · Finanzas personales</p><h1>{title}</h1><p className="page-subtitle">{subtitle}</p></div><span className="profile-pill">{user?.nombre || 'Invitado'} <b>●</b></span></header>{children}</main></div>
}

export function DashboardReact() {
  const [state, setState] = useState({ trans: [], metas: [], perfil: {} }); const [loading, setLoading] = useState(true)
  useEffect(() => { Promise.all([request('/transacciones/', { headers: auth() }), request('/metas/', { headers: auth() }), request('/perfil/', { headers: auth() })]).then(([trans, metas, perfil]) => setState({ trans, metas, perfil })).catch(() => {}).finally(() => setLoading(false)) }, [])
  const ingresos = state.trans.filter((item) => item.tipo === 'ingreso').reduce((sum, item) => sum + Number(item.monto), 0)
  const gastos = state.trans.filter((item) => item.tipo === 'gasto').reduce((sum, item) => sum + Number(item.monto), 0)
  return <Shell title={`Hola, ${state.perfil.nombre || 'bienvenido'} 👋`} subtitle="Este es el pulso de tus finanzas este mes." active="/dashboard"><div className="stat-grid"><Stat label="Ingresos" value={money(ingresos)} icon="↗" tone="cyan" /><Stat label="Gastos" value={money(gastos)} icon="↘" tone="pink" /><Stat label="Balance" value={money(ingresos - gastos)} icon="◒" tone="green" /><Stat label="Metas activas" value={state.metas.length} icon="◎" tone="yellow" /></div><div className="dashboard-grid"><section className="surface"><Title text="Accesos rápidos" /><div className="quick-grid"><Quick href="/finanzas" icon="💸" text="Registrar movimiento" /><Quick href="/chat" icon="🤖" text="Preguntar a FinanBot" /><Quick href="/simulador" icon="📈" text="Simular inversión" /><Quick href="/perfil" icon="◎" text="Completar perfil" /></div></section><section className="surface"><Title text="Últimos movimientos" />{loading ? <Loading /> : <MovementList items={state.trans.slice(0, 7)} />}</section></div><section className="surface goals-panel"><Title text="Tus metas de ahorro" /><div className="goal-grid">{state.metas.slice(0, 3).map((goal) => <Goal key={goal.id} goal={goal} />)}{!state.metas.length && <Empty text="Crea tu primera meta desde Perfil." />}</div></section></Shell>
}

export function FinanceReact() {
  const [items, setItems] = useState([]); const [message, setMessage] = useState(''); const [form, setForm] = useState({ tipo: 'gasto', monto: '', categoria: 'Alimentación', descripcion: '' })
  const load = () => request('/transacciones/', { headers: auth() }).then(setItems).catch((error) => setMessage(error.message))
  useEffect(load, [])
  async function save(event) { event.preventDefault(); try { await request('/transacciones/', { method: 'POST', headers: jsonHeaders(), body: JSON.stringify({ ...form, monto: Number(form.monto), fecha: new Date().toISOString().slice(0, 10) }) }); setForm({ ...form, monto: '', descripcion: '' }); setMessage('Movimiento guardado correctamente.'); load() } catch (error) { setMessage(error.message) } }
  async function remove(id) { if (!confirm('¿Eliminar este movimiento?')) return; try { await request(`/transacciones/${id}`, { method: 'DELETE', headers: auth() }); load() } catch (error) { setMessage(error.message) } }
  const totals = items.reduce((result, item) => ({ ...result, [item.tipo]: result[item.tipo] + Number(item.monto) }), { ingreso: 0, gasto: 0 })
  return <Shell title="Mis finanzas" subtitle="Registra, filtra y entiende cada movimiento." active="/finanzas"><div className="stat-grid compact"><Stat label="Ingresos" value={money(totals.ingreso)} icon="↗" tone="cyan" /><Stat label="Gastos" value={money(totals.gasto)} icon="↘" tone="pink" /><Stat label="Balance" value={money(totals.ingreso - totals.gasto)} icon="◒" tone="green" /><Stat label="Movimientos" value={items.length} icon="#" tone="yellow" /></div><div className="finance-layout"><section className="surface form-surface"><Title text="Nuevo movimiento" /><form onSubmit={save}><div className="segmented"><button type="button" className={form.tipo === 'gasto' ? 'selected gasto' : ''} onClick={() => setForm({ ...form, tipo: 'gasto' })}>💸 Gasto</button><button type="button" className={form.tipo === 'ingreso' ? 'selected ingreso' : ''} onClick={() => setForm({ ...form, tipo: 'ingreso' })}>💰 Ingreso</button></div><Field label="Monto" type="number" value={form.monto} onChange={(value) => setForm({ ...form, monto: value })} required /><label>Categoría<select value={form.categoria} onChange={(event) => setForm({ ...form, categoria: event.target.value })}>{['Alimentación', 'Transporte', 'Arriendo', 'Salud', 'Entretenimiento', 'Educación', 'Ropa', 'Servicios', 'Salario', 'Freelance', 'Otros gastos'].map((item) => <option key={item}>{item}</option>)}</select></label><Field label="Descripción" value={form.descripcion} onChange={(value) => setForm({ ...form, descripcion: value })} placeholder="Ej. Mercado del mes" /><button className="primary-action" type="submit">Guardar movimiento →</button></form>{message && <p className="form-message">{message}</p>}</section><section className="surface"><Title text="Movimientos recientes" /><MovementList items={items} onRemove={remove} /></section></div></Shell>
}

export function CalendarReact() {
  const today = new Date(); const [month, setMonth] = useState(today.getMonth() + 1); const [year, setYear] = useState(today.getFullYear()); const [data, setData] = useState(null); const [selected, setSelected] = useState(null); const [error, setError] = useState('')
  useEffect(() => { request(`/calendario/${year}/${month}`, { headers: auth() }).then(setData).catch((e) => setError(e.message)) }, [year, month])
  const days = data ? new Date(year, month, 0).getDate() : 0; const first = new Date(year, month - 1, 1).getDay(); const cells = Array.from({ length: first }, () => null).concat(Array.from({ length: days }, (_, index) => index + 1)); const byDay = data?.movimientos?.reduce((all, item) => ({ ...all, [Number(item.fecha.slice(-2))]: [...(all[Number(item.fecha.slice(-2))] || []), item] }), {}) || {}
  function move(step) { const next = month + step; if (next === 0) { setMonth(12); setYear(year - 1) } else if (next === 13) { setMonth(1); setYear(year + 1) } else setMonth(next) }
  async function download(format) { const response = await fetch(`${API}/calendario/reporte/${year}/${month}?formato=${format}`, { headers: auth() }); if (!response.ok) { setError('Este mes no tiene movimientos para exportar.'); return } const blob = await response.blob(); const url = URL.createObjectURL(blob); const link = document.createElement('a'); link.href = url; link.download = `finanbot-${year}-${month}.${format === 'pdf' ? 'pdf' : 'xlsx'}`; link.click(); URL.revokeObjectURL(url) }
  return <Shell title="Calendario financiero" subtitle="Revisa tus movimientos día por día y exporta el mes." active="/calendario"><div className="calendar-toolbar"><button onClick={() => move(-1)}>←</button><h2>{data?.nombre_mes || 'Cargando'} {year}</h2><button onClick={() => move(1)}>→</button><button className="secondary-action" onClick={() => download('pdf')}>PDF</button><button className="secondary-action" onClick={() => download('excel')}>Excel</button></div>{error && <div className="inline-alert">{error}</div>}<div className="calendar-summary"><Stat label="Ingresos" value={money(data?.total_ingresos)} icon="↗" tone="cyan" /><Stat label="Gastos" value={money(data?.total_gastos)} icon="↘" tone="pink" /><Stat label="Balance" value={money(data?.balance)} icon="◒" tone="green" /></div><div className="calendar-layout"><section className="surface calendar-board"><div className="weekdays">{['Dom', 'Lun', 'Mar', 'Mié', 'Jue', 'Vie', 'Sáb'].map((day) => <b key={day}>{day}</b>)}</div><div className="calendar-grid">{cells.map((day, index) => <button className={`${day && byDay[day] ? 'has-data' : ''} ${selected === day ? 'selected' : ''}`} key={`${day}-${index}`} onClick={() => day && setSelected(day)}>{day}<span>{day && byDay[day]?.length ? `${byDay[day].length} mov.` : ''}</span></button>)}</div></section><section className="surface day-panel"><Title text={selected ? `Movimientos del día ${selected}` : 'Selecciona un día'} />{selected && byDay[selected]?.length ? <MovementList items={byDay[selected]} /> : <Empty text="No hay movimientos para mostrar." />}</section></div></Shell>
}

export function ProfileReact() {
  const [profile, setProfile] = useState({}); const [metas, setMetas] = useState([]); const [form, setForm] = useState({}); const [message, setMessage] = useState(''); const [goal, setGoal] = useState({ nombre: '', monto_objetivo: '', fecha_limite: '', modo: 'manual', monto_automatico: '', dia_automatico: '' })
  const load = () => Promise.all([request('/perfil/', { headers: auth() }), request('/metas/', { headers: auth() })]).then(([user, goals]) => { setProfile(user); setForm(user); setMetas(goals) }).catch((e) => setMessage(e.message)); useEffect(load, [])
  async function saveProfile(event) { event.preventDefault(); try { await request('/perfil/', { method: 'PUT', headers: jsonHeaders(), body: JSON.stringify({ nombre: form.nombre, rol: form.rol, ingreso_mensual: Number(form.ingreso_mensual), meta_ahorro: Number(form.meta_ahorro), fecha_salario: form.fecha_salario }) }); setMessage('Perfil actualizado.'); load() } catch (e) { setMessage(e.message) } }
  async function saveGoal(event) { event.preventDefault(); try { await request('/metas/', { method: 'POST', headers: jsonHeaders(), body: JSON.stringify({ ...goal, monto_objetivo: Number(goal.monto_objetivo), monto_automatico: goal.monto_automatico ? Number(goal.monto_automatico) : null, dia_automatico: goal.dia_automatico ? Number(goal.dia_automatico) : null }) }); setGoal({ ...goal, nombre: '', monto_objetivo: '' }); setMessage('Meta creada.'); load() } catch (e) { setMessage(e.message) } }
  async function removeGoal(id) { if (!confirm('¿Eliminar esta meta?')) return; await request(`/metas/${id}`, { method: 'DELETE', headers: auth() }); load() }
  return <Shell title="Mi perfil" subtitle="Configura tu información, regla de ahorro y metas." active="/perfil"><div className="profile-grid"><section className="surface profile-card"><div className="profile-avatar">{(profile.nombre || 'U')[0]}</div><h2>{profile.nombre || 'Usuario'}</h2><p>{profile.correo || ''}</p><span className="status-badge">● Perfil activo</span><div className="profile-facts"><Info label="Ingreso mensual" value={money(profile.ingreso_mensual)} /><Info label="Meta de ahorro" value={money(profile.meta_ahorro)} /></div></section><section className="surface"><Title text="Datos personales" /><form onSubmit={saveProfile}><Field label="Nombre" value={form.nombre || ''} onChange={(value) => setForm({ ...form, nombre: value })} /><label>Rol<select value={form.rol || ''} onChange={(e) => setForm({ ...form, rol: e.target.value })}><option value="">Selecciona un rol</option>{['estudiante', 'empleado', 'independiente', 'emprendedor'].map((role) => <option key={role}>{role}</option>)}</select></label><Field label="Ingreso mensual" type="number" value={form.ingreso_mensual || ''} onChange={(value) => setForm({ ...form, ingreso_mensual: value })} /><Field label="Meta de ahorro" type="number" value={form.meta_ahorro || ''} onChange={(value) => setForm({ ...form, meta_ahorro: value })} /><Field label="Fecha de salario" type="date" value={form.fecha_salario || ''} onChange={(value) => setForm({ ...form, fecha_salario: value })} /><button className="primary-action">Guardar cambios →</button></form>{message && <p className="form-message">{message}</p>}</section></div><div className="profile-grid goals-section"><section className="surface"><Title text="Crear meta de ahorro" /><form onSubmit={saveGoal}><Field label="Nombre" value={goal.nombre} onChange={(value) => setGoal({ ...goal, nombre: value })} placeholder="Viaje, vivienda..." /><Field label="Monto objetivo" type="number" value={goal.monto_objetivo} onChange={(value) => setGoal({ ...goal, monto_objetivo: value })} /><Field label="Fecha límite" type="date" value={goal.fecha_limite} onChange={(value) => setGoal({ ...goal, fecha_limite: value })} /><button className="primary-action">Crear meta →</button></form></section><section className="surface"><Title text="Metas actuales" /><div className="goal-list">{metas.map((item) => <div className="goal-row" key={item.id}><Goal goal={item} /><button className="icon-danger" onClick={() => removeGoal(item.id)}>×</button></div>)}{!metas.length && <Empty text="Todavía no tienes metas." />}</div></section></div></Shell>
}

export function SimulationReact() {
  const [form, setForm] = useState({ capital_inicial: 1000000, tasa_retorno: 10, plazo_meses: 12, aporte_mensual: 0 }); const [result, setResult] = useState(null); const [error, setError] = useState('')
  async function calculate(event) { event.preventDefault(); try { setResult(await request('/simulaciones/calcular', { method: 'POST', headers: jsonHeaders(), body: JSON.stringify({ ...form, capital_inicial: Number(form.capital_inicial), tasa_retorno: Number(form.tasa_retorno), plazo_meses: Number(form.plazo_meses), aporte_mensual: Number(form.aporte_mensual) }) })) } catch (e) { setError(e.message) } }
  return <Shell title="Simulador" subtitle="Compara escenarios antes de invertir." active="/simulador"><div className="simulator-layout"><form className="surface simulation-form" onSubmit={calculate}><Title text="Parámetros" /><Field label="Capital inicial" type="number" value={form.capital_inicial} onChange={(v) => setForm({ ...form, capital_inicial: v })} /><Field label="Tasa anual (%)" type="number" value={form.tasa_retorno} onChange={(v) => setForm({ ...form, tasa_retorno: v })} /><Field label="Plazo (meses)" type="number" value={form.plazo_meses} onChange={(v) => setForm({ ...form, plazo_meses: v })} /><Field label="Aporte mensual" type="number" value={form.aporte_mensual} onChange={(v) => setForm({ ...form, aporte_mensual: v })} /><button className="primary-action">Calcular escenario →</button></form><section className="surface simulation-result">{error && <div className="inline-alert">{error}</div>}{result ? <><small>VALOR FINAL PROYECTADO</small><strong>{money(result.valor_final)}</strong><p>Ganancia estimada: {money(result.ganancia)} · Rentabilidad: {result.rentabilidad}%</p><div className="scenario-list">{result.escenarios?.map((scenario) => <div key={scenario.nombre}><span>{scenario.nombre}</span><b>{money(scenario.valor_final)}</b></div>)}</div></> : <Empty text="Completa los parámetros para ver el resultado." />}</section></div></Shell>
}

export function LearnReact() {
  const [query, setQuery] = useState(''); const [articles, setArticles] = useState([]); const [selected, setSelected] = useState(null); const [glossary, setGlossary] = useState([])
  useEffect(() => { Promise.all([request('/aprende/articulos'), request('/aprende/glosario')]).then(([all, terms]) => { setArticles(all.articulos || []); setGlossary(terms.terminos || []) }).catch(() => {}) }, [])
  async function search(event) { event.preventDefault(); if (!query.trim()) return; const result = await request(`/aprende/buscar?q=${encodeURIComponent(query)}`); setArticles(result.articulos || []) }
  return <Shell title="Aprende" subtitle="Herramientas y conceptos para tomar mejores decisiones." active="/aprende"><form className="learn-search" onSubmit={search}><input value={query} onChange={(e) => setQuery(e.target.value)} placeholder="Busca CDT, ahorro, deudas..." /><button className="primary-action">Buscar →</button></form><div className="article-grid">{articles.map((item) => <button className="article" key={item.id} onClick={() => setSelected(item)}><span>{item.emoji || '📚'}</span><small>{item.categoria}</small><h2>{item.titulo}</h2><p>{item.resumen || item.descripcion}</p></button>)}</div><section className="surface glossary"><Title text="Glosario financiero" /><div className="glossary-grid">{glossary.slice(0, 12).map((item) => <div key={item.termino || item.nombre}><b>{item.termino || item.nombre}</b><p>{item.definicion || item.descripcion}</p></div>)}</div></section>{selected && <div className="modal-backdrop" onClick={() => setSelected(null)}><article className="article-modal" onClick={(e) => e.stopPropagation()}><button onClick={() => setSelected(null)}>×</button><span>{selected.emoji || '📚'}</span><h2>{selected.titulo}</h2><p>{selected.contenido || selected.descripcion || selected.resumen}</p></article></div>}</Shell>
}

export function RecommendationsReact() { const [items, setItems] = useState([]); const [filter, setFilter] = useState('todos'); useEffect(() => { request('/recomendaciones/', { headers: auth() }).then(setItems).catch(() => {}) }, []); const visible = useMemo(() => filter === 'todos' ? items : items.filter((item) => item.tipo === filter), [items, filter]); return <Shell title="Recomendaciones" subtitle="Ideas personalizadas para cuidar tu dinero." active="/recomendaciones"><div className="filter-row">{['todos', 'alerta', 'advertencia', 'exito', 'info'].map((item) => <button className={filter === item ? 'active' : ''} onClick={() => setFilter(item)} key={item}>{item}</button>)}</div><div className="recommendation-grid">{visible.map((item, index) => <article className={`recommendation ${item.tipo || 'info'}`} key={item.id || index}><span>{item.icono || '✦'}</span><small>{item.tipo || 'info'} · {item.prioridad || 'Media'}</small><h2>{item.titulo || item.nombre}</h2><p>{item.descripcion || item.mensaje}</p><a href={item.link || '/chat'}>Pedir ayuda a FinanBot →</a></article>)}{!visible.length && <Empty text="No hay recomendaciones para este filtro." />}</div></Shell> }

export function ExportReact() { const [message, setMessage] = useState(''); async function download(type) { try { const response = await fetch(`${API}/exportar/${type}`, { headers: auth() }); if (!response.ok) throw new Error('No se pudo generar el reporte'); const blob = await response.blob(); const url = URL.createObjectURL(blob); const link = document.createElement('a'); link.href = url; link.download = `finanbot-reporte.${type === 'excel' ? 'xlsx' : 'pdf'}`; link.click(); URL.revokeObjectURL(url) } catch (e) { setMessage(e.message) } } return <Shell title="Exportar reportes" subtitle="Descarga un resumen de tus finanzas." active="/exportar"><div className="export-grid"><button className="export-card excel" onClick={() => download('excel')}><span>▦</span><h2>Reporte Excel</h2><p>Analiza tus movimientos con todo el detalle.</p><strong>Descargar →</strong></button><button className="export-card pdf" onClick={() => download('pdf')}><span>▤</span><h2>Reporte PDF</h2><p>Un resumen limpio para guardar o compartir.</p><strong>Descargar →</strong></button></div>{message && <div className="inline-alert">{message}</div>}</Shell> }

export function OnboardingReact() { const [role, setRole] = useState(''); const [income, setIncome] = useState(''); const [saving, setSaving] = useState(false); const [error, setError] = useState(''); async function finish() { if (!role || Number(income) < 10000) { setError('Elige un perfil e ingresa un ingreso mensual válido.'); return } setSaving(true); try { await request('/perfil/', { method: 'PUT', headers: jsonHeaders(), body: JSON.stringify({ rol: role.toLowerCase(), ingreso_mensual: Number(income), onboarding_completado: true }) }); location.href = '/' } catch (e) { setError(e.message) } finally { setSaving(false) } } return <div className="auth-screen"><div className="auth-card onboarding"><div className="auth-logo">✦</div><p className="eyebrow">Primer paso</p><h1>Construyamos tu plan.</h1><p className="muted">Cuéntanos un poco sobre tu situación para personalizar FinanBot.</p><div className="role-grid">{['Estudiante', 'Empleado', 'Independiente', 'Emprendedor'].map((item) => <button className={role === item ? 'selected' : ''} onClick={() => setRole(item)} key={item}>{item}</button>)}</div><Field label="Ingreso mensual" type="number" value={income} onChange={setIncome} placeholder="Ej. 2000000" />{error && <div className="inline-alert">{error}</div>}<button className="primary-action" disabled={saving} onClick={finish}>{saving ? 'Guardando...' : 'Continuar →'}</button></div></div> }

function Stat({ label, value, icon, tone }) { return <div className={`stat-card ${tone}`}><span>{icon}</span><small>{label}</small><strong>{value}</strong></div> }
function Title({ text }) { return <div className="section-title"><h2>{text}</h2><span>•</span></div> }
function Quick({ href, icon, text }) { return <a href={href}>{icon}<span>{text}</span></a> }
function Field({ label, value, onChange, type = 'text', placeholder = '', required = false }) { return <label>{label}<input required={required} type={type} value={value ?? ''} placeholder={placeholder} onChange={(event) => onChange(event.target.value)} /></label> }
function MovementList({ items, onRemove }) { return <div className="movement-list">{items.map((item) => <div className="movement" key={item.id}><span>{item.tipo === 'gasto' ? '💸' : '💰'}</span><div><b>{item.categoria}</b><small>{item.descripcion || 'Sin descripción'} · {item.fecha || ''}</small></div><strong className={item.tipo}>{money(item.monto)}</strong>{onRemove && <button className="icon-danger" onClick={() => onRemove(item.id)}>×</button>}</div>)}{!items.length && <Empty text="No hay movimientos para mostrar." />}</div> }
+function Goal({ goal }) { const percentage = Number(goal.porcentaje || 0); return <div className="goal"><div><b>{goal.nombre}</b><small>{money(goal.monto_actual)} de {money(goal.monto_objetivo)}</small></div><strong>{percentage}%</strong><div className="progress"><i style={{ width: `${percentage}%` }} /></div></div> }
+function Info({ label, value }) { return <div className="info-card"><small>{label}</small><strong>{value}</strong></div> }
+function Empty({ text }) { return <div className="empty-state">◎<p>{text}</p></div> }
+function Loading() { return <div className="loading-state"><i /><i /><i /></div> }
